[package]
name = "coffee_stylus"
version = "0.1.0"
description = "Coffee-Stylus Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

        
